### PR TITLE
Fix skipping bug

### LINKED ISSUE #2: Bug: Findup skips a directory level
Hey there...

So while I was developing something around this library, I found a slight bug in its behavior. It seems to skip a directory level each iteration.

To prove this, I added a few print statements to the `lookupFile` function:
```
 func lookupFile(basepath string, filename string) (string, error) {
        matches, err := filepath.Glob(path.Join(basepath, filename))
+       fmt.Println("Checking path:", basepath)
+       fmt.Println("Matches:", matches)
```

Using a slightly modified Unit test, I found that if the file findup is looking for is in the same directory, no problems. Searching for: `findup.go` we have a few cases here:
```
Checking path: /Users/tbrown/dev/github.com/h2non/findup
Matches: [/Users/tbrown/dev/github.com/h2non/findup/findup.go]
```

In a subdirectory, two layers down, also no problem:
```
Checking path: /Users/tbrown/dev/github.com/h2non/findup/.tmp/a
Matches: []
Checking path: /Users/tbrown/dev/github.com/h2non/findup
Matches: [/Users/tbrown/dev/github.com/h2non/findup/findup.go]
```

But if we go an odd number of directories down, we never get a match:
```
Checking path: /Users/tbrown/dev/github.com/h2non/findup/.tmp/a/b
Matches: []
Checking path: /Users/tbrown/dev/github.com/h2non/findup/.tmp
Matches: []
Checking path: /Users/tbrown/dev/github.com/h2non
Matches: []
Checking path: /Users/tbrown/dev
Matches: []
Checking path: /Users
Matches: []
Checking path: /
Matches: []
```

I believe this is because of this line: https://github.com/h2non/findup/blob/77fb97516883ed0fd3257a6c8062d1d06eed5789/findup.go#L27

Where we're asking for the `path.Dir(basepath)`, which get's us one directory up, but then we're also joining with `..`, which puts us yet another directory up, effectively skipping a directory level.

I'm putting together an MR to fix this, and enhancing the Unit Tests to detect this problem as well. Hopefully you don't mind the enhancement! :) 

Cheers,
Ty

### PR DESCRIPTION
**Pull request by TyBrown**
Fixes #2

### CODE REVIEW

File: findup_test.go [hunk 1]
```diff
@@ -35,17 +36,24 @@ func TestCannotFindGlobFileInTheCurrentDirectory(t *testing.T) {
...
+	testFindFilePath(t, ".tmp/a/b/c")
+}
+
+func testFindFilePath(t *testing.T, dirPath string) {
+	cwd, _ := os.Getwd()
+	goodPath := getFullPath("findup.go")
+
+	tmpDir := filepath.Join(cwd, dirPath)
 	os.MkdirAll(tmpDir, 0666)
-	os.Chdir(tmpDir)
```
Comment (TyBrown) [inline findup_test.go:40]: I removed the `os.Chdir()` calls in this test, because it seems like subsequent calls to `os.Getwd()` would still return the old value, which is why I also switched away from calling `Find()` in the unit test, to checking the underlying function call `lookupFile()` instead.
